services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.26-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
    - RABBITMQ_DEFAULT_USER=rabbitmq
    - RABBITMQ_DEFAULT_PASS=filas-teste
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
    - MYSQL_DATABASE=filas_consumer
    - MYSQL_PASSWORD=root
    - MYSQL_ROOT_PASSWORD=root